title: "Juan B Cabral"
description: "Personal home page"

theme: minima

minima:
  skin: solarized
      
header_pages:
  - software.md
  - publications.md
  - courses.md
  - students.md
  - links.md

