---
# https://github.com/pages-themes/cayman

theme: jekyll-theme-cayman
layout: page

title: "JBC"
description: "Personal home page"

sitecolor: "#205692"
logo: assets/imgs/quatrope_logo.png
favicon: assets/imgs/favicon.ico

license_link: legal
coc_link: coc
contact_link: contact

navbar:
    - title: Software
      link: software

    - title: Publications
      link: publications

    - title: Links
      link: links
