remote_theme: https://github.com/jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

title: Juan B Cabral
description: Juan B Cabral - Personal homepage
author: JBC

github_username:  leliel12


minima:
  skin: auto
  social_links:
    - { platform: github,         user_url: "https://github.com/leliel12" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qhWYqpoAAAAJ&hl=en" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/juanbcabral" }

      
header_pages:
  - software.md
  - publications.md
  - courses.md
  - students.md
  - links.md


